version: '3'

services:

  mongo:
    image: mongo
    ports:
      - "27888:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge